use_frameworks!

target 'LPADialNumberKeyboard_Example' do
  pod 'LPADialNumberKeyboard', :path => '../'

  target 'LPADialNumberKeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
